server:
  port: 8301
  servlet:
    context-path: /

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
  thymeleaf:
    suffix: .html
    prefix: classpath:/page/

castle:
  upload:
    # 自行配置可访问的路径
    fileDomain: http://up.icuapi.com/docpreview
    fileServerPath: /www/wwwroot/up.icuapi.com/docpreview/  #原始文件的服务器存储位置
